### ISSUE TITLE
GitHub OAuth failing

### ISSUE THREAD

**Issue by arashnrim** [project-lumiere/lumiere#55]
Hey!

I noticed that something went wrong when trying to sign in to Lumiere using Github. All that GitHub returns is a 404 page, and looking at the link the 404 for was given when trying to authorise (at `https://github.com/login/oauth/authorize?...`).

Let's see if we can do anything about it. This might be a critical issue, so let's try to fix it ASAP!

**Comment by AnthonyKuang** [comment]
Can you try emptying your browser cache and hard reload?

https://www.hexnode.com/mobile-device-management/help/how-to-clear-cache-and-hard-reload-browsers/#using-developer-tools

**Comment by AnthonyKuang** [comment]
Nevermind, auth is still broken. I'll try reversing some PRs because it was working yesterday evening.

**Comment by AnthonyKuang** [comment]
Auth should be fixed now! I inputted the wrong env vars 😱

**Comment by arashnrim** [comment]
Haha, no worries! Let me give it a try on my end, too.

**Comment by arashnrim** [comment]
Seems all good to me! 👍 

I'll close this issue since it's resolved. Thanks for the quick action! 🙌
